### ISSUE TITLE
Encoding problem with Redmine 1.4.4

### ISSUE THREAD

**Issue by brunetton** [maxtepkeev/python-redmine#71] opened 2015-01-20 14:19 UTC
Hi, 

I'm stucked in my [Redmine Time Sync] (https://github.com/brunetton/redminetimesync) project with an utf-8 problem with Redmine 1.4.4 

```python
from redmine import Redmine
redmine = Redmine('http://localhost:3000', key='key')

redmine.time_entry.create(
    spent_on='2015-01-07',
    issue_id=1,
    hours=1,
    activity_id=9,
    comments=u'Comment with accent: é'
)
```

This generate an 500 error from Redmine :

```
ServerError                               Traceback (most recent call last)
<ipython-input-3-05520c487a73> in <module>()
      4     hours=1,
      5     activity_id=9,
----> 6     comments=u'é'
      7 )

/home/bruno/dev/python-redmine/redmine/managers.py in create(self, **fields)
    178         # resources are created via PUT, so we should check for this
    179         try:
--> 180             response = self.redmine.request('post', url, data=data)
    181         except ResourceNotFoundError:
    182             response = self.redmine.request('put', url, data=data)

/home/bruno/dev/python-redmine/redmine/__init__.py in request(self, method, url, headers, params, data, raw_response)
    139             raise ValidationError(to_string(', '.join(e if is_string(e) else ': '.join(e) for e in errors)))
    140         elif response.status_code == 500:
--> 141             raise ServerError
    142 
    143         raise UnknownError(response.status_code)

ServerError: Redmine returned internal error, perhaps you are doing something wrong
```

Does anybody can test that with a more recent Redmine version ? I've some time consuming problems while installing newest redmine versions.

Thanks

**Comment by maxtepkeev** [comment] 2015-01-20 15:16
Hi Bruno,

Works perfectly fine for me in Redmine 2.3.3 both with Python 2.7 and 3.4

**Comment by maxtepkeev** [comment] 2015-02-03 14:54
Hi Bruno,

Any news on this ?

**Comment by maxtepkeev** [comment] 2015-02-24 19:20
Hi Bruno,

I've finally managed to install Redmine 1.4.4 inside a VirtualBox.

Unfortunately (or fortunately) I can't reproduce your problem here, so I believe that this is related to your concrete installation, here's my configuration, maybe it will help you:

```
Redmine 1.4.4.stable (SQLite)
Rails 2.3.14
Ruby 2.1.2
Ubuntu 14.10
```

I'm closing this issue because there's nothing else I can do to help. If you find out the cause of the problem, please let me know.

Thanks.

**Closed by maxtepkeev** 2015-02-24 19:20 UTC
Labels: question
