### ISSUE TITLE
Problem updating Parent Title of Wiki Page

### ISSUE THREAD

**Issue by kcollins-ene** [maxtepkeev/python-redmine#195] opened 2018-02-19 23:58 UTC
Attempting to update the parent title of a wiki page after it has been created fails with a `Text field cannot be blank` validation error.

Running this:
```python
redmine.project.create(name='Test Project', 
	identifier='test-project'
)
redmine.wiki_page.create(project_id='test-project', title='ParentTitle', text='ParentText')
redmine.wiki_page.create(project_id='test-project', title='ChildTitle', text='ChildText')
redmine.wiki_page.update('ChildTitle', project_id='test-project', parent_title='ParentTitle')
```

Produces this:
```
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "/usr/local/lib/python3.6/site-packages/redminelib/managers.py", line 221, in update
    return self.redmine.engine.request(self.resource_class.http_method_update, url, data=data)
  File "/usr/local/lib/python3.6/site-packages/redminelib/engines/base.py", line 75, in request
    return self.process_response(self.session.request(method, url, **kwargs), return_raw)
  File "/usr/local/lib/python3.6/site-packages/redminelib/engines/base.py", line 167, in process_response
    raise exceptions.ValidationError(', '.join(': '.join(e) if isinstance(e, list) else e for e in errors))
redminelib.exceptions.ValidationError: Text field cannot be blank
```

The use case I'm trying to achieve is a project copy.  If I create all of the new Wiki pages with their parent associations I encounter errors if I create them in the wrong order.  Instead, I'm collecting the parent-title associations from the source project and am wanting to go through and update the `parent_title` field on each of the pages after they've been created (in a flat structure).

Using `python-redmine (2.0.2)` against a Redmine 3.4.4 instance for testing.  Thoughts?

**Comment by maxtepkeev** [comment] 2018-02-21 07:56
Hi Kevin,

Yes, I can confirm that this problem exists. There's no Python-Redmine fault in it though. ``ValidationError`` you're getting is coming from the Redmine itself, because for some reason the ``text`` attribute is always required (I should fix this in Python-Redmine docs for update operation). So unless this will be fixed on the Redmine side there's nothing we can really do about it.

The workaround I can recommend is to always sent the text attribute:

```python
redmine.wiki_page.create(project_id='test-project', title='ParentTitle', text='ParentText')
child = redmine.wiki_page.create(project_id='test-project', title='ChildTitle', text='ChildText')
redmine.wiki_page.update('ChildTitle', project_id='test-project', parent_title='ParentTitle', child.text)
```

I believe you can create all the wikipages first and put the created objects in a dictionary preserving the parent-child hierarchy and then iterate over this dictionary doing updates to the children assigning them to their respective parent pages and sending the same ``text`` attribute again.

Hope that helps.

**Comment by kcollins-ene** [comment] 2018-02-21 14:04
Thanks @maxtepkeev, I did indeed end up working around it..  I set the `parent_title` as it needed to be set and then collected the new wiki page resource objects into a list (without running `save()`).  I then determined ordering breadth-first and iterated that order calling the `save()`..  So a little extra effort but a decent result..  Thanks for the feedback--I was wondering whether that was under your control or not (since I saw the 422 result coming back)..  Thankfully this isn't a show-stopper.

**Comment by maxtepkeev** [comment] 2018-02-21 14:21
Cool, good to know that you solved the problem.

Python-Redmine contains almost no validation and/or response attributes hardcoding, i.e. everything is constructed dynamically based on the response from Redmine, so in 99.9% of the cases if you have problems with something, it's a Redmine's fault, because unfortunately it's API has a very inconsistent design and Python-Redmine tries it's best to hide this inconsistency from the user to make working with Redmine a breeze :)

**Closed by maxtepkeev** 2018-02-21 14:21 UTC
Labels: question
