### ISSUE TITLE
Issue wasn't updated

### ISSUE THREAD

**Issue by chevi** [maxtepkeev/python-redmine#75] opened 2015-02-01 15:15 UTC
Hi

I'm trying to update an issue
with Redmine version 2.5.2.stable, python 2.7, latest python-redmine and requests

```
>>> issue = server.issue.get(10316)
>>> issue.status
<redmine.resources.IssueStatus #1 "New">
>>> issue.status = "Resolved"
>>> issue.save()
True
>>> issue = server.issue.get(10316)
>>> issue.status
<redmine.resources.IssueStatus #1 "New">
```

When I check on the web, I see that issue "Updated less than a minute ago."
but nothing really changed. The same with updating notes and other fields.

I also tried this variant
```
>>> server.issue.update(10316, description='sss')
True
```
Result is the same unfortunately (no changes on web)

What am I doing wrong? Or is it a bug?

Thanks!

**Comment by maxtepkeev** [comment] 2015-02-01 18:10
Hi,

As for the first problem (updating status), you should use ``status_id`` and not ``status``, see [docs](http://python-redmine.readthedocs.org/resources/issue.html#update) e.g. ``status_id=X`` where X is the desired status id.

As for the second problem, looks like everything should be all right, but if you say that it's not working please be sure that you're using either the user with administrative rights or the user who created the issue to update the issue description.

**Comment by chevi** [comment] 2015-02-01 19:30
Hi

No matter what field I try to update, it wasn't updated. (in my start message was my fault with status_id, but even with correct no help)

Here I tried to change only subject
```

>>> server.issue.update(10315, subject='sss')
True
```
On script I used the same account of administrator as for web. But result is the same: ticket is updated but without any updates. Here is the screenshot
![test10315](https://cloud.githubusercontent.com/assets/1729590/5993424/3caec2c4-aa61-11e4-9fb2-cb9fd72d5e25.jpeg)


What else can it be?

Name: python-redmine
Version: 1.0.2
Name: requests
Version: 2.5.1

Best wishes, thanks!

**Comment by maxtepkeev** [comment] 2015-02-02 07:10
Your problem looks very similar to the one described [here](http://python-redmine.readthedocs.org/faq.html#create-update-delete-resource-operations-doesn-t-work). Please let me know if that doesn't help.

**Comment by chevi** [comment] 2015-02-02 07:36
Thanks, sorry that I didn't look to FAQ. Maybe it's a good idea to make a Note in the Config article about this differences in connection.

But actually when I connected by https, I got:
```
>>> server = Redmine('https://...', key='...')
>>> issue = server.issue.get(10315)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/redmine/managers.py", line 127, in get
    return self.resource_class(self, self.retrieve()[0])
  File "/usr/local/lib/python2.7/dist-packages/redmine/managers.py", line 60, in retrieve
    response = self.redmine.request('get', self.url, params=dict(self.params, limit=limit, offset=offset))
  File "/usr/local/lib/python2.7/dist-packages/redmine/__init__.py", line 116, in request
    response = getattr(requests, method)(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

**Comment by maxtepkeev** [comment] 2015-02-02 07:48
Well, this is the error from requests library, which basically says that it can't connect to your server by https. Does the https connection works for you via web browser ? If yes then you should try to connect by using raw requests (without python-redmine), e.g. something like this:

```python
import requests
response = requests.get('https://your-server-url/issues/10315', params={'key': 'your-api-key'})
print(response.text)
```

If that doesn't also work you should ask the requests guys about what can be wrong either with requests or with your server configuration. Please let me know how that goes.

**Comment by chevi** [comment] 2015-02-02 08:53
Sorry, I didn't look into the settings of redmine and start to connect with python and https. That's why there was the error in requests.
So redmine works with HTTP and I connect by HTTP with requests. Unfortunately I'm on the same step as was in my comment with picture.

I'll try to downgrade requests library. Or maybe you have another ideas how to debug this issue.

Thanks

**Comment by maxtepkeev** [comment] 2015-02-02 11:18
Hmm, that's really strange... I don't have time to test new requests right now, so can you please do 2 things:

1) Try to update an issue on http://demo.redmine.org and see if it works here
2) Try to update an issue on your server and then see if you see the updates via web browser via http://your-redmine/issues/10315.json

Thanks

**Comment by chevi** [comment] 2015-02-02 19:05
I tested on another our server with redmine 2.4.1.stable
And it works there. Can it be some configuration of the redmine server or not?
If you have possibility check this on version 2.5.2.stable on your side and have time, we can check is it a bug or not. If you haven't - let's close this issue

Thanks a lot for your help!

**Comment by maxtepkeev** [comment] 2015-02-03 07:45
Interesting... I'll definitely test this on Redmine 2.5.2.stable, probably not right now, but I'll try to do it this week. Frankly speaking I don't think that this is a Redmine or Python-Redmine bug, I believe that this is some misconfiguration on your server or maybe some caching issues if you have something on the front, e.g. nginx (this is why I asked you to try to update an issue on your server and then see if you see the updates via web browser via http://your-redmine/issues/10315.json, because json isn't usually cached, have you tried that btw ?)

When I'll test everything on Redmine 2.5.2 I'll let you know, let's keep this issue open until we find out the cause of this strange behaviour. I hope that we'll manage to find out what it is because it may help other users with the same problem in the future.

**Comment by maxtepkeev** [comment] 2015-02-03 17:07
Hi,

I just tested issue updates on 2.5.2, here is the complete environment I used:
```
Environment:
  Redmine version                2.5.2.stable
  Ruby version                   2.0.0-p481 (2014-05-08) [universal.x86_64-darwin14]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
```

I've tried Python 2.6, 2.7, 3.2, 3.3, 3.4 and everything works perfectly fine here. So I'm 100% sure that it's some kind of a server misconfiguration on your side or caching issues like I described in previous message. I'm closing this issue because unfortunately there's nothing I can do to help you here.

If you manage to solve this problem, please write what it was to this issue, that could help other people in the future.

Thanks.

**Closed by maxtepkeev** 2015-02-03 17:07 UTC
Labels: question
