### ISSUE TITLE
Error on Windows Servers: "path too long for Windows"

### ISSUE THREAD

**Issue by jonfen** [maxtepkeev/python-redmine#214] opened 2018-10-22 17:33 UTC
`__init__.py:104 os.path.isfile(f)` produces the error "path too long for Windows" when sending a file-like object using [redminelib.managers.ResourceManager.create uploads](https://python-redmine.com/resources/issue.html?highlight=stringio), such as the full DOM of a webpage (ex: new XMLSerializer().serializeToString(document);).  There are several places where os.path is being used.

**Comment by maxtepkeev** [comment] 2018-10-29 12:06
Hi @jonfen 

Thanks for the report and apologize for the late reply.

It would be great if you could provide an example to reproduce this behaviour as I have no windows servers to experiment with.

Thanks.

**Comment by jonfen** [comment] 2018-10-29 16:40
@maxtepkeev, unfortunately, you can't reproduce this without a windows environment, but they are easy to set up on a mac or Linux doing the following:

1. Install [virtualbox](https://www.virtualbox.org/) 
2. Download a free [windows virtual development environment](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines)

`
from io import StringIO
...
create_issue = redmine.issue.new()
...
create_issue.uploads = [{'path': StringIO(request.form['current_page_markup'])}]
...
create_issue.save()
`
where
`var current_page_markup = new XMLSerializer().serializeToString(document);`

**Comment by maxtepkeev** [comment] 2018-10-30 11:17
@jonfen Thanks, yep, I understand that I need a windows environment and it's not a problem to launch a virtual container or an EC2 machine in AWS, what I meant was that because I don't work in a windows environment for more than 15 years I would need a reproducible example and your code helps, the only question I still have is what should be contained in `document` variable that you pass to `new XMLSerializer().serializeToString()` ?

Does it matter what kind of XML should be inside or what length should it have, i.e. how big it should be to reproduce this bug. Would be great if you could attach your document that is causing this if it's not confidential of course.

Thanks in advance.

**Comment by jonfen** [comment] 2018-10-30 13:50
@maxtepkeev, I am not sure what the exact windows path character limit is.   I just used `var current_page_markup = new XMLSerializer().serializeToString(document);` on a very large page. 
 `document` is pre-defined by the browser, that javascript command will dump the entire page you are on.  However, it really shouldn't matter what you string you use to exceed the character limit.   I would just view source, copy and paste the rendered html from any complicated site (5000+ lines).  

I do not prefer windows either, so I thank you for looking into the problem.

**Comment by jonfen** [comment] 2018-11-12 23:04
[The path length limit is 260.](https://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows)  So check the len of stream = f before calling os.path calls -- you should be good.

**Comment by maxtepkeev** [comment] 2019-01-02 20:47
@jonfen I've finally managed to find some time and work on this issue. After a few tests I came to the conclusion that there's nothing to fix, because the size of a file-like object doesn't matter, even on Windows it works perfectly fine.

The problem here was that you were sending the contents of the ``request.form['current_page_markup']`` request **without** enclosing it in a file-like object, this is why you got this error, you can try your code from https://github.com/maxtepkeev/python-redmine/issues/214#issuecomment-433983785 and see that it works perfectly, then remove the ``StringIO`` object and send the content directly and you'll get exactly the error described.

I'm closing this issue, but feel free to reopen if I missed something. Thanks.

**Closed by maxtepkeev** 2019-01-02 20:47 UTC
Labels: bug
